name: typescript-bot watchdog

on:
  schedule:
    # Hourly
    - cron: '15 1/2 * * *'
  workflow_dispatch:

jobs:
  watchdog:
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/setup-for-scripts

      - run: node ./scripts/watchdog-typescript-bot.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
